# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

flutter_application_path = '../mm_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'mm' do
	
  install_all_flutter_pods(flutter_application_path)

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for mm


  

  # UI wedges
  pod 'QMUIKit'

  # Tab bar/page bar
  pod 'TYPagerController'

   # Auto layout
   pod 'Masonry'
   pod 'SnapKit', '~> 5.7.0'

  # YYKit
  pod 'YYKit'

  # Alert/sheet
  pod 'HWPanModal', '~> 0.9.9'
  pod 'LEEAlert'

  # Alert/loading
  pod 'SVProgressHUD'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'Toast'

  # RAC
  pod 'ReactiveCocoa', '~> 10.1'

  # webview Bridge
	pod 'WKWebViewJavascriptBridge'

  # data base
  pod 'WCDB.swift'
  pod 'FMDB'

  


  # base pods
# UI debug Tool
pod 'LookinServer', :configurations => ['Debug']

# theme
pod 'LEETheme'

# Module
pod 'CTMediator'


  target 'mmTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mmUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end
