# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# flutter
flutter_application_path = '../mm_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

# pod module
def uibase
  # UI wedges
  pod 'QMUIKit'
  # Tab bar/page bar
  pod 'TYPagerController'
  # Auto layout
  pod 'Masonry'
  pod 'SnapKit', '~> 5.7.0'
  # Alert/sheet
  pod 'HWPanModal', '~> 0.9.9'
  pod 'LEEAlert'
  # Alert/loading
  pod 'SVProgressHUD'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'Toast'
  # YYKit
  pod 'YYKit', git: 'https://github.com/SAGESSE-CN/YYKit.git'
  # Nav
  pod 'CWLateralSlide'
  pod 'FDFullscreenPopGesture'
  # emptyView
  pod 'DZNEmptyDataSet'
end

def uitools
  # calendar
  pod 'FSCalendar'
  # badgeView
  pod 'JSBadgeView'
  # mapView
  pod 'ClusterKit'
  # charts
  pod 'DGCharts'
  # link preview
  pod 'SwiftLinkPreview'
end

def imageVideoAudio
  pod 'YBImageBrowser'
  pod 'BRPickerView'
  pod 'TZImagePickerController'
  # image picker/clip
  pod 'TOCropViewController'
  # Gif
  pod 'FLAnimatedImage'
  pod 'SDWebImage'
  pod 'Kingfisher'
  pod 'ZFPlayer'
end

def network
  pod 'YTKNetwork'
  pod 'AFNetworking'
end

def database
  # data base
  pod 'WCDB.swift'
  pod 'FMDB'
end

def tools
  # UI debug Tool
  pod 'LookinServer', :configurations => ['Debug']
  # RAC OC
  pod 'ReactiveObjC'
  # RAC Swift
  pod 'ReactiveCocoa'
end

def common
  # Date
  pod 'DateTools'
  # keyboard
  pod 'IQKeyboardManager'
  # RAC
  pod 'ReactiveCocoa', '~> 10.1'
  # webview Bridge
	pod 'WKWebViewJavascriptBridge'
  # theme
  pod 'LEETheme'
  # Module
  pod 'CTMediator'
end

target 'mm' do
  install_all_flutter_pods(flutter_application_path)
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for mm
  uibase
  uitools
  imageVideoAudio
  database
  tools
  common

  target 'mmTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mmUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end
